### ISSUE TITLE
Input dataset

### ISSUE THREAD

**Issue by ozaltun** [lamaoudi/883_idtrees#1]
The goal of this issue is to determine the input dataset that will be used for classification.

At the moment, there is a dimensionality issue associated with each `(X, y)` data point. X, being the deliminated data, has a high number of bands and is images. Given that we don't have a large dataset, we need to figure out methods of extracting the most important information from these bands.

One method @lamaoudi mentioned is to use PCA on bands.

**Comment by lamaoudi** [comment]
So I took a deeper look at how they dealt with bounding boxes, class-labels, and images. They extract the labels and bounding boxes by referencing the "data_train_mitree" csv file. The csv file provides the location of the bounding box by specifying the min- max- row and col indices of the extent of the box in one of the 85 HSI images. So we could use that to extract separate images for a bounding box and include the class name. 

What the team initially did: The function get_hsi_pixels basically checks the class of each pixel, vertically stacks all 369 bands of a single pixel with the first row as the class name, for all pixels in all 85 images. Which means instead of running an object-level classification (tree crown extent) they do a pixel-level classification. I personally think the former would be better since it allows us to average across each band for multiple pixels and might lead to better results. But the data is already prepared in pixel-level classification mode, so it would avoid re-processing the data.... idk.

**Comment by lamaoudi** [comment]
Ok I was able to make it object-level vs. pixel-level. In other words, I was able to extract each HSI image within a bounding box and its corresponding Class ID. Each image is a tensor with shape [rows, cols, 369]. # rows= # cols

**Comment by ozaltun** [comment]
@lamaoudi awesome, so just to make sure I understood what you said above:
- `/data/data_train_mitree.csv` is the guideline file that provides labels, location of image, and bounding box of each entry in our dataset.
- (Done previously): A [function](https://github.com/lamaoudi/883_idtrees/blob/3945010d2c6d6cebc956edc93218c5d544a552a5/idtrees/utils/read_tifs.py#L50) that creates (X, y) where `X_i` is a single pixel in one of the images of length 369 and `y_i` is the associated tree label for that pixel. This is a **pixel-level** dataset.
- (Done by @lamaoudi): Creating an **object-level** dataset (X, y), where `X_i` is a tensor of [rows, cols, 369] and `y_i` is the associated label. Have you written the code, if so can you push?

Potential next TODOs:

- [ ] Decide on how to pre-process `X_i`.
- [ ] Implement pre-process. 

I'm happy to take a shot at both of these later this afternoon!!

**Comment by lamaoudi** [comment]
@ozaltun when choosing between which pre-process one thing that comes to mind is the fact that the object-level analysis would have different sized objects/images. Can you foresee that being an issue? I think it should be OK.. but I'm not confident.

**Comment by lamaoudi** [comment]
OK i'm realizing (and correct me if I'm wrong) choosing between object or pixel-level classification only matters if we were applying a CNN (something that actually is learning contextual parameters). I assume that if we're using an SVM it'll be pixel-level anyway.... right?

**Comment by lamaoudi** [comment]
@ozaltun see master.ipynb for everything.

**Comment by lamaoudi** [comment]
> OK i'm realizing (and correct me if I'm wrong) choosing between object or pixel-level classification only matters if we were applying a CNN (something that actually is learning contextual parameters). I assume that if we're using an SVM it'll be pixel-level anyway.... right?

well no, because we'd be inputing it as a tensor. Scratch earlier comment.

**Comment by lamaoudi** [comment]
From Literature on Reducing Dimensionality of Data: 

1. Forward Minimum Noise Fraction (MNF) transform. Method reduces data redundancy and identifies bands containing the most variance. MNF creates outputs of uncorrelated bands, ranked from highest eigenvalue (with most meaningful bands) to lowest eigenvalue (containing noise-filled bands). 
2. Work by Pal and Mather (2006) showed that a 40-band dataset was optimal for processing times of HSI. PCA was used for band selection- can asses the importance of each spectral band in each principal component by looking at the magnitude of factor loadings which correspond tot the correlations between bands and principal components. Higher loadings indicate more important bands, then you can just use top-40 bands.

**Comment by ozaltun** [comment]
@lamaoudi some minor updates:
- I have added a [new](https://github.com/lamaoudi/883_idtrees/blob/master/notebooks/master-BO%20version.ipynb) notebook based on your work in `master.ipynb`.
- I have left the way you decided to deal with the images (PCA) as is.
- Some additional pre-processing I have added: re-balancing, removing Other, standardizing the data.

On some of the pre-processing:
1. Re-balancing: The data is imbalanced as you have previously mentioned. It is also important to have equal number (or close to equal) of each class when training. If you look at the confusion matrix in your notebook, you can see that class 23, with the least number of observations, does terribly. So I just do something super simple, resample images from the dataset.
2. I have decided to remove "Other": I think this is probably confusing the classification algorithm since there isn't a similarity between these trees. Is this okay in your opinion? Can add back, but think it is probably best to leave out.
3. Standardizing data: Sometimes it can help to normalize the data (de-mean and make standard deviation 1).

**Comment by lamaoudi** [comment]
1. Looks good to me. 
2. Sure! The concept of an 'Other' was brought up in the competition docs, but I can 100% see how it would reduce performance to include it. 
3. Good idea! Hadn't thought of it.
