### ISSUE TITLE
Choosing classes

### ISSUE THREAD

**Issue by ozaltun** [lamaoudi/883_idtrees#2]
Accurately classifying all classes in the dataset is out of the scope of this project. The goal of this issue is to determine which classes we want to use in our classification (probably n of the highest occurring classes).

**Comment by lamaoudi** [comment]
Top Classes were identified, Not included classes were saved as "other". Tried to make sure there was no huge class imbalance....

**Comment by ozaltun** [comment]
@lamaoudi nice! We can randomly re-sample in the training to make sure there is no imbalance. Could you push the code for this too? 😊

**Comment by lamaoudi** [comment]
Everything's been pushed!

**Comment by lamaoudi** [comment]
Chosen 6 classes, and re-grouped other species into an "other"
